FROM sdesilva26/spark_base

#COPY ./requirements.txt .
#RUN pip install -r requirements.txt

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"

EXPOSE 4040 8888