FROM sdesilva26/spark_base

COPY ./resources/requirements.txt .
RUN pip install -r requirements.txt

COPY ./examples/ ./examples/

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"
ENV SPARK_EXECUTOR_MEMORY 6G

EXPOSE 4040 8888